version: '3.5'

services:
  postgres:
    container_name: postgres_website
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-website}
      POSTGRES_USER: ${POSTGRES_USER:-website}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-website}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
